/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as HelpRouteImport } from './routes/help'
import { Route as MissedOpportunitiesRouteImport } from './routes/missed-opportunities'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReadinessRouteImport } from './routes/readiness'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as EligibilityIdRouteImport } from './routes/eligibility/$id'
import { Route as SchemesIndexRouteImport } from './routes/schemes/index'
import { Route as SchemesIdRouteImport } from './routes/schemes/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const MissedOpportunitiesRoute = MissedOpportunitiesRouteImport.update({
  id: '/missed-opportunities',
  path: '/missed-opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadinessRoute = ReadinessRouteImport.update({
  id: '/readiness',
  path: '/readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const EligibilityIdRoute = EligibilityIdRouteImport.update({
  id: '/eligibility/$id',
  path: '/eligibility/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemesIndexRoute = SchemesIndexRouteImport.update({
  id: '/schemes/',
  path: '/schemes/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemesIdRoute = SchemesIdRouteImport.update({
  id: '/schemes/$id',
  path: '/schemes/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/applications': typeof ApplicationsRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/help': typeof HelpRoute
  '/missed-opportunities': typeof MissedOpportunitiesRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/readiness': typeof ReadinessRoute
  '/recommendations': typeof RecommendationsRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/eligibility/$id': typeof EligibilityIdRoute
  '/schemes/$id': typeof SchemesIdRoute
  '/schemes/': typeof SchemesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/applications': typeof ApplicationsRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/help': typeof HelpRoute
  '/missed-opportunities': typeof MissedOpportunitiesRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/readiness': typeof ReadinessRoute
  '/recommendations': typeof RecommendationsRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/eligibility/$id': typeof EligibilityIdRoute
  '/schemes/$id': typeof SchemesIdRoute
  '/schemes': typeof SchemesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/applications': typeof ApplicationsRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/help': typeof HelpRoute
  '/missed-opportunities': typeof MissedOpportunitiesRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/readiness': typeof ReadinessRoute
  '/recommendations': typeof RecommendationsRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/eligibility/$id': typeof EligibilityIdRoute
  '/schemes/$id': typeof SchemesIdRoute
  '/schemes/': typeof SchemesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/applications'
    | '/dashboard'
    | '/documents'
    | '/help'
    | '/missed-opportunities'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/readiness'
    | '/recommendations'
    | '/saved'
    | '/settings'
    | '/eligibility/$id'
    | '/schemes/$id'
    | '/schemes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/applications'
    | '/dashboard'
    | '/documents'
    | '/help'
    | '/missed-opportunities'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/readiness'
    | '/recommendations'
    | '/saved'
    | '/settings'
    | '/eligibility/$id'
    | '/schemes/$id'
    | '/schemes'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/applications'
    | '/dashboard'
    | '/documents'
    | '/help'
    | '/missed-opportunities'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/readiness'
    | '/recommendations'
    | '/saved'
    | '/settings'
    | '/eligibility/$id'
    | '/schemes/$id'
    | '/schemes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApplicationsRoute: typeof ApplicationsRoute
  DashboardRoute: typeof DashboardRoute
  DocumentsRoute: typeof DocumentsRoute
  HelpRoute: typeof HelpRoute
  MissedOpportunitiesRoute: typeof MissedOpportunitiesRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  ReadinessRoute: typeof ReadinessRoute
  RecommendationsRoute: typeof RecommendationsRoute
  SavedRoute: typeof SavedRoute
  SettingsRoute: typeof SettingsRoute
  EligibilityIdRoute: typeof EligibilityIdRoute
  SchemesIdRoute: typeof SchemesIdRoute
  SchemesIndexRoute: typeof SchemesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missed-opportunities': {
      id: '/missed-opportunities'
      path: '/missed-opportunities'
      fullPath: '/missed-opportunities'
      preLoaderRoute: typeof MissedOpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readiness': {
      id: '/readiness'
      path: '/readiness'
      fullPath: '/readiness'
      preLoaderRoute: typeof ReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eligibility/$id': {
      id: '/eligibility/$id'
      path: '/eligibility/$id'
      fullPath: '/eligibility/$id'
      preLoaderRoute: typeof EligibilityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemes/': {
      id: '/schemes/'
      path: '/schemes'
      fullPath: '/schemes/'
      preLoaderRoute: typeof SchemesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemes/$id': {
      id: '/schemes/$id'
      path: '/schemes/$id'
      fullPath: '/schemes/$id'
      preLoaderRoute: typeof SchemesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApplicationsRoute: ApplicationsRoute,
  DashboardRoute: DashboardRoute,
  DocumentsRoute: DocumentsRoute,
  HelpRoute: HelpRoute,
  MissedOpportunitiesRoute: MissedOpportunitiesRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  ReadinessRoute: ReadinessRoute,
  RecommendationsRoute: RecommendationsRoute,
  SavedRoute: SavedRoute,
  SettingsRoute: SettingsRoute,
  EligibilityIdRoute: EligibilityIdRoute,
  SchemesIdRoute: SchemesIdRoute,
  SchemesIndexRoute: SchemesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
